[/]
animate-appicon-hover=false
animate-appicon-hover-animation-extent={'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}
animate-appicon-hover-animation-type='PLANK'
appicon-margin=0
appicon-padding=4
available-monitors=[0]
dot-position='BOTTOM'
dot-style-focused='METRO'
dot-style-unfocused='DOTS'
hide-overview-on-startup=true
hotkeys-overlay-combo='TEMPORARILY'
intellihide=false
isolate-monitors=false
isolate-workspaces=false
leftbox-padding=-1
multi-monitors=true
overview-click-to-exit=false
panel-anchors='{"0":"MIDDLE","1":"MIDDLE","2":"MIDDLE"}'
panel-element-positions='{"0":[{"element":"showAppsButton","visible":false,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"dateMenu","visible":true,"position":"centerMonitor"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"centerBox","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":false,"position":"stackedBR"}],"1":[{"element":"showAppsButton","visible":false,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"dateMenu","visible":true,"position":"centerMonitor"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"centerBox","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":false,"position":"stackedBR"}],"2":[{"element":"showAppsButton","visible":false,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"dateMenu","visible":true,"position":"centerMonitor"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"centerBox","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":false,"position":"stackedBR"}]}'
panel-element-positions-monitors-sync=true
panel-lengths='{"0":100,"1":100,"2":100}'
panel-positions='{"0":"TOP","1":"TOP","2":"TOP"}'
panel-sizes='{"0":32,"1":32,"2":32}'
primary-monitor=0
show-favorites=true
show-favorites-all-monitors=true
show-running-apps=true
status-icon-padding=-1
stockgs-keep-top-panel=false
trans-use-custom-bg=false
trans-use-custom-opacity=false
trans-use-dynamic-opacity=false
tray-padding=-1
window-preview-title-position='TOP'
