[/]
animate-appicon-hover=false
animate-appicon-hover-animation-extent={'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}
animate-appicon-hover-animation-type='PLANK'
appicon-margin=0
appicon-padding=4
available-monitors=[0, 1]
dot-color-1='#eeeeee'
dot-color-2='#eeeeee'
dot-color-3='#eeeeee'
dot-color-4='#eeeeee'
dot-color-dominant=false
dot-color-override=true
dot-color-unfocused-different=false
dot-position='BOTTOM'
dot-style-focused='METRO'
dot-style-unfocused='DOTS'
focus-highlight=true
focus-highlight-color='#eeeeee'
focus-highlight-dominant=false
group-apps=true
hide-overview-on-startup=true
hot-keys=false
hotkeys-overlay-combo='TEMPORARILY'
intellihide=false
intellihide-animation-time=200
intellihide-behaviour='FOCUSED_WINDOWS'
intellihide-close-delay=400
intellihide-enable-start-delay=2000
intellihide-hide-from-windows=false
intellihide-key-toggle=@as []
intellihide-key-toggle-text=''
intellihide-only-secondary=false
intellihide-pressure-threshold=100
intellihide-pressure-time=1000
intellihide-show-in-fullscreen=false
intellihide-use-pressure=false
isolate-monitors=false
isolate-workspaces=false
leave-timeout=0
leftbox-padding=-1
multi-monitors=true
overview-click-to-exit=false
panel-anchors='{"0":"MIDDLE","1":"MIDDLE","2":"MIDDLE"}'
panel-element-positions='{"0":[{"element":"showAppsButton","visible":false,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"dateMenu","visible":true,"position":"centerMonitor"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"centerBox","visible":true,"position":"stackedTL"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":false,"position":"stackedBR"}],"1":[{"element":"showAppsButton","visible":false,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"dateMenu","visible":true,"position":"centerMonitor"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"centerBox","visible":true,"position":"stackedTL"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":false,"position":"stackedBR"}],"2":[{"element":"showAppsButton","visible":false,"position":"stackedTL"},{"element":"activitiesButton","visible":false,"position":"stackedTL"},{"element":"leftBox","visible":true,"position":"stackedTL"},{"element":"taskbar","visible":true,"position":"stackedTL"},{"element":"dateMenu","visible":true,"position":"centerMonitor"},{"element":"rightBox","visible":true,"position":"stackedBR"},{"element":"centerBox","visible":true,"position":"stackedBR"},{"element":"systemMenu","visible":true,"position":"stackedBR"},{"element":"desktopButton","visible":false,"position":"stackedBR"}]}'
panel-element-positions-monitors-sync=true
panel-lengths='{"0":100,"1":100,"2":100}'
panel-positions='{"0":"TOP","1":"TOP","2":"TOP"}'
panel-sizes='{"0":32,"1":32,"2":32}'
primary-monitor=0
progress-show-count=true
secondarymenu-contains-appmenu=true
secondarymenu-contains-showdetails=false
show-appmenu=false
show-apps-icon-file=''
show-apps-override-escape=true
show-favorites=true
show-favorites-all-monitors=true
show-running-apps=true
show-window-previews-timeout=0
status-icon-padding=-1
stockgs-keep-dash=false
stockgs-keep-top-panel=false
trans-bg-color='#808080'
trans-dynamic-anim-target=0.80000000000000004
trans-dynamic-anim-time=300
trans-dynamic-behavior='ALL_WINDOWS'
trans-dynamic-distance=20
trans-panel-opacity=0.40000000000000002
trans-use-custom-bg=true
trans-use-custom-gradient=true
trans-use-custom-opacity=true
trans-use-dynamic-opacity=true
tray-padding=-1
window-preview-hide-immediate-click=true
window-preview-title-position='BOTTOM'
